ip_mode: tun # tun or tap, default tun
dns_mode: udp # tcp or udp, default tcp
socks_server: 127.0.0.1
socks_port: 1080
remote_dns_server: 8.8.8.8
remote_dns_port: 53
local_dns_port: 53
gw: 10.0.0.1
addr: 10.0.0.2
netmask: 255.255.255.0
